name: Webhook-Trigger
on: 
  workflow_dispatch:
    inputs:
      name:
        required: false
        description: Name
        type: string

jobs:
  trigger:
    runs-on: self-hosted
    steps:
      - name: Log the Trigger
        run: echo "Workflow Triggered through webhook"

      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Load Dataset
        run: python3 src.data.loader.py
