name: Webhook-Trigger
on: 
  workflow_dispatch:
    inputs:
      name:
        required: false
        description: Name
        type: string

jobs:
  load_dataset:
    runs-on: self-hosted
    steps:
      - name: Log the Trigger
        run: echo "Workflow Triggered through webhook"

      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install Libraries
        run:  pip install -r requirements.txt

      - name: Load Dataset
        run: |
          mkdir dataset
          python3 -m src.data.loader

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: raw_dataset
          path: dataset/dataset.csv

      

